print("Welcome to the Name to Number Convertor")
firstName = input("Enter your First Name\n")
lastName = input("Enter your Last Name\n")
print("Your Name Size is",end=" ")
print (len(firstName)+len(lastName))
